/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jd_ebook_rights_rpc_drm_DrmLib */

#ifndef _Included_com_jd_ebook_rights_rpc_drm_DrmLib
#define _Included_com_jd_ebook_rights_rpc_drm_DrmLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jd_ebook_rights_rpc_drm_DrmLib
 * Method:    GenerateRightFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jobject JNICALL Java_com_jd_ebook_rights_rpc_drm_DrmLib_GenerateRightFile
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);
/*
 * Class:     com_jd_ebook_rights_rpc_drm_DrmLib
 * Method:    GenerateRightFileBuf
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/jd/ebook/rights/rpc/drm/DrmObject;
 */
JNIEXPORT jobject JNICALL Java_com_jd_ebook_rights_rpc_drm_DrmLib_GenerateRandom
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
