/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jingdong_app_reader_data_Ebr */

#ifndef _Included_com_jingdong_app_reader_data_Ebr
#define _Included_com_jingdong_app_reader_data_Ebr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jingdong_app_reader_data_Ebr
 * Method:    API01
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
//JNIEXPORT jstring JNICALL Java_com_jingdong_app_reader_data_Ebr_API01
JNIEXPORT jstring JNICALL Java_com_jingdong_app_reader_data_DrmTools_API01
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jingdong_app_reader_data_Ebr
 * Method:    API02
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jingdong_app_reader_data_DrmTools_API02
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
